version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    expose:
      - 8080
  
  node_backend:
    build: ./node
    ports:
      - "5000:5000"
    expose:
      - 5000

  go_backend:
    build: ./go
    ports:
      - "3000:3000"
    expose:
      - 3000
