version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
  
  backend:
    build: ./backend
    ports:
      - "8081:8081"
